name: RK-Economy
author: T4TU_
version: 2
main: me.t4tu.rkeconomy.Economy
depend: [RK-Core, LangUtils]
api-version: 1.13
commands:
    rahat:
    raha:
    money:
    balance:
    bal:
    kultakolikko:
    hopeakolikko:
    shekki:
    sekki:
    kauppa:
    kaupat:
    torikoju:
    torikojut:
    tori:
    liikekiinteistö:
    liikekiinteistöt:
    shop: